.travis.yml
=> testing commit

client/app.js, client/components/all-products.js, client/components/index.js, client/components/one-product.js, client/routes.js, client/store/index.js, client/store/product.js, server/api/products.js
- added a single product api route
- created a product reducer and redux store
- created basic react components for all-products and one-product
- created render routes
- render appears fine for /products and /products/:productId
closes #15  and #16
=> basic react functionality

server/api/index.js, server/api/orderItem.js
=> added orderItem API route

client/app.js, client/components/one-product.js, client/store/cart.js, client/store/index.js, server/api/orderItem.js, server/db/models/index.js
=> add to cart is functional

client/components/cart.js, client/components/navbar.js, client/routes.js, script/seed.js
added frontend route/link & added seed
=> feat(components/Cart): added frontend route/link & added seed

client/components/navbar.js
=> fixed navbar

server/api/orderItem.js, server/api/users.js
=> fixed req.body

client/components/app.js, client/components/checkoutForm.js, package-lock.json, package.json, public/index.html, server/api/payment.js
feat(checkout/payment): stripe components added, needs to be tested and checked...
[1] needs token
[2] double check if template needs updates on any specific fields
=> feat(checkout/payment): stripe components added, needs to be tested and checked

client/components/cart.js, client/components/one-product.js, client/store/cart.js, client/store/history.js, server/api/cart.js, server/db/models/category.js
Also created update quantity (wip api + redux)
and separated order history into its own redux component
=> Delete Cart Item Working

client/components/cart.js
before it showed up as blank.
unfortunately, had a tough time to get quantity to increase somehow, when you add the same product. It might be the associations and Sequelize that make it a bit tricky.
=> small fix(quantity for each item now showing up in cart)

client/components/one-product.js, script/seed.js
single product images now render
(also fleshed out the descriptions a bit)
=> fixed seed file

.gitignore, client/components/auth-form.js, client/components/checkoutMain.js, client/components/one-product.js, client/components/user-home.js, package-lock.json, package.json, public/index.html, public/style.css, server/api/api.spec.js, server/api/users.js, server/db/models/user.js
slight styling tweaks so the landing page looks a little fancier (loosely copied from The Sill's website)
=> Minor home tweaks

client/components/cart.js
=> feat(components/cart): cart view fleshed out, ready for styling

server/api/cart.js, server/auth/google.js
- google oauth  refactored for updated user model  
- delete route authenticates correctly i hope
=> fix(auth/google & api/cart): google oauth and delete authentication

client/components/checkoutForm.js, client/components/checkoutMain.js, client/components/checkoutReview.js, package-lock.json, package.json, server/api/payment.js
=> fixed(component/checkout): payment goes through/ updated checkout

.travis.yml
=> feat(travis.yml): adds continuous deployment

client/components/orderHistory.js, client/routes.js
- fixed general page render for / routes
- empty order history page renders
=> feat(components/routes and orderHistory): small fixes

client/components/one-product.js, server/api/users.js, server/auth/index.js
changed new user sign up. all is functional again
=> new user fixes

server/api/api.spec.js
=> feat (api.spec.js) added one test

client/components/checkoutFormPage.js, client/components/checkoutReviewPage.js, client/components/one-product.js, client/components/orderHistory.js, client/store/cart.js, client/store/order.js, public/style.css
cleaned up console logs, one-product page, etc
=> Detail fix
